swerve_controller:
  ros__parameters:

    robot_base_frame: base_footprint

    twist_topic: nav_vel

    position_controller_name: "drive_module_steering_angle_controller"
    velocity_controller_name: "drive_module_velocity_controller"

    steering_joints:
      - joint_chassis_to_steering_left_front
      - joint_chassis_to_steering_right_front
      - joint_chassis_to_steering_left_rear
      - joint_chassis_to_steering_right_rear

    drive_joints:
      - joint_steering_to_wheel_left_front
      - joint_steering_to_wheel_right_front
      - joint_steering_to_wheel_left_rear
      - joint_steering_to_wheel_right_rear

    # Additional topics
    odom_topic: /odom
    joint_state_topic: joint_states
    
    # TF settings
    publish_tf: false  # EKF가 odom->base_footprint TF를 발행하므로 비활성화
    cycle_fequency: 20

    # QoS (depth only for simplicity)
    pub_qos_depth: 10
    sub_qos_depth: 10

    # Steering angle normalization (radians)
    enable_steering_angle_normalization: false
    #steering angle limits 추가해야함
    #####################################################################
    # Motion profile
    motion_profile_type: linear   # linear | s_curve | trapezoidal

    robot_geometry:
      wheel_base: 1.756 # The distance between the front and rear steering axles (meters)
      wheel_track: 0.930 # The distance between the left and right steering axles (meters)
      wheel_radius: 0.205 # The radius of the drive wheels (meters)
      wheel_width: 0.15 # The width of the drive wheels (meters)

    # Drive module specific parameters
    drive_modules:
      left_front:
        steering_motor_maximum_velocity: 1.57 # rad/s
        steering_motor_minimum_acceleration: 0.1 # rad/s^2
        steering_motor_maximum_acceleration: 1.57 # rad/s^2
        drive_motor_maximum_velocity: 1.6 # m/s
        drive_motor_minimum_acceleration: 0.1 # m/s^2
        drive_motor_maximum_acceleration: 1.6 # m/s^2
      left_rear:
        steering_motor_maximum_velocity: 1.57
        steering_motor_minimum_acceleration: 0.1
        steering_motor_maximum_acceleration: 1.57
        drive_motor_maximum_velocity: 1.6
        drive_motor_minimum_acceleration: 0.1
        drive_motor_maximum_acceleration: 1.6
      right_rear:
        steering_motor_maximum_velocity: 1.57
        steering_motor_minimum_acceleration: 0.1
        steering_motor_maximum_acceleration: 1.57
        drive_motor_maximum_velocity: 1.6
        drive_motor_minimum_acceleration: 0.1
        drive_motor_maximum_acceleration: 1.6
      right_front:
        steering_motor_maximum_velocity: 1.57
        steering_motor_minimum_acceleration: 0.1
        steering_motor_maximum_acceleration: 1.57
        drive_motor_maximum_velocity: 1.6
        drive_motor_minimum_acceleration: 0.1
        drive_motor_maximum_acceleration: 1.6
