front_scanner:
  ros__parameters:
    frame_id: "lidar_front"
    sensor_ip: "192.168.10.88"
    host_ip: "192.168.10.66"
    host_udp_port: 2111
    interface_ip: "0.0.0.0"
    channel_enabled: true
    skip: 0
    angle_start: 0.0
    angle_end: 0.0
    time_offset: 0.0
    general_system_state: true
    derived_settings: true
    measurement_data: true
    intrusion_data: true
    application_io_data: true
    use_persistent_config: false
    min_intensities: 0.0

rear_scanner:
  ros__parameters:
    frame_id: "lidar_back"
    sensor_ip: "192.168.10.99"
    host_ip: "192.168.10.66"
    host_udp_port: 2112
    interface_ip: "0.0.0.0"
    channel_enabled: true
    skip: 0
    angle_start: 0.0
    angle_end: 0.0
    time_offset: 0.0
    general_system_state: true
    derived_settings: true
    measurement_data: true
    intrusion_data: true
    application_io_data: true
    use_persistent_config: false
    min_intensities: 0.0